version: '3.8'

services:
  db:
    image: postgres:17
    container_name: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_SCHEMA: metadata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - dev_vkr

  pgadmin:
    image: dpage/pgadmin4:9.13
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8085:80"
    networks:
      - dev_vkr

networks:
  dev_vkr:
    name: dev_vkr
    driver: bridge